const sampleData = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: '123456',
      role: 'admin',
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: '123456',
      role: 'user',
    },
  ],
  products: [
    {
      name: 'Rhino Premier Roofing Sheet',
      slug: 'rhino-premier-roofing-sheet',
      category: "Roofing",
      description: 'Back by 60 years of trusted legacy, Rhino Premier Roofing Sheets available at Prime Hardware in a 1750mm size and classic Non-Color finish deliver unmatched strength, leak resistance, and long lasting durability to withstand nature’s toughest weather. Designed for quick, low maintenance installation, these high-quality sheets fit together seamlessly to keep your building completely protected, ensuring a smart, reliable investment that stands the test of time.',
      images: [
        '/images/sample-products/p1-1.jpg',
        '/images/sample-products/p1-2.jpg',
      ],
      price: 3870,
      brand: 'Rhino',
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: '/images/banner-1.jpg',
    },
    {
      name: 'Nippon Roofing Paint - Water Base',
      slug: 'Nippon-Roofing-Paint---Water-Base',
      category: "Paint",
      description: 'Premium acrylic water-based roof coating specially engineered for exterior roofing and architectural surfaces. Durable, flexible, and enriched with biocides and algaecides to resist mold, algae, and microbial growth. Delivers outstanding adhesion, excellent coverage, and long-lasting protection against harsh tropical climates while enhancing surface appearance and durability. Formulated to resist peeling, cracking, and fading, ensuring reliable performance and lasting colour retention in demanding weather conditions.',
      images: [
        '/images/sample-products/p2-1.jpg',
        '/images/sample-products/p2-2.jpg',
      ],
      price: 2312,
      brand: 'Nippon',
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: '/images/banner-2.jpg',
    },
    {
      name: 'Nippon Wall Filler',
      slug: 'nippon-wall-filler',
      category: "Paint",
      description: 'Nippolac Acrylic Wall Filler is designed for interior plastered surfaces and previously painted walls, offering excellent filling properties. It effectively hides surface imperfections and helps achieve a smooth, high-quality finish. It also reduces paint absorption, helping to lower the cost of the first coat of paint while improving overall coverage and appearance.',
      images: [
        '/images/sample-products/p3-1.jpg',
        '/images/sample-products/p3-2.jpg',
      ],
      price: 712,
      brand: 'Nippon',
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Nippon Ceiling White',
      slug: 'nippon-ceiling-white',
      category: "Paint",
      description: 'Premium ceiling paint for a smooth, durable finish',
      images: [
        '/images/sample-products/p4-1.jpg',
        '/images/sample-products/p4-2.jpg',
      ],
      price: 1328,
      brand: 'Nippon',
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Nippon Weatherproof Brilliant White',
      slug: 'nippon-weatherproof-brilliant-white',
      category: "Paint",
      description: 'Nippolac Weatherproof Acrylic Exterior Emulsion is specially formulated to provide a durable and attractive finish for exterior walls. Its tough and flexible composition contains biocides and algaecides that help prevent the growth of mould, algae, and other microorganisms. Resistant to salt spray and designed to withstand harsh tropical weather conditions, it offers long-lasting protection while enhancing the appearance of exterior surfaces.',
      images: [
        '/images/sample-products/p5-1.jpg',
        '/images/sample-products/p5-2.jpg',
      ],
      price: 2184,
      brand: 'Nippon',
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Nippon Weatherproof - Colors',
      slug: 'nippon-weatherproof-colors',
      category: "Paint",
      description: 'Nippolac Weatherproof Acrylic Exterior Emulsion is specially formulated to provide a durable and attractive finish for exterior walls. Its tough and flexible composition contains biocides and algaecides that help prevent the growth of mould, algae, and other microorganisms. Resistant to salt spray and designed to withstand harsh tropical weather conditions, it offers long-lasting protection while enhancing the appearance of exterior surfaces.',
      images: [
        '/images/sample-products/p6-1.jpg',
        '/images/sample-products/p6-2.jpg',
      ],
      price: 2512,
      brand: 'Nippon',
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;
