const sampleData = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: '123456',
      role: 'admin',
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: '123456',
      role: 'user',
    },
    {
      name: 'Sarah Jenkins',
      email: 'sarah@example.com',
      password: '123456',
      role: 'user',
    },
    {
      name: 'David Perera',
      email: 'david@example.com',
      password: '123456',
      role: 'user',
    },
  ],
  products: [
    {
      name: 'Rhino Premier Roofing Sheet',
      slug: 'rhino-premier-roofing-sheet',
      category: "Roofing",
      description: 'Back by 60 years of trusted legacy, Rhino Premier Roofing Sheets available at Prime Hardware in a 1750mm size and classic Non-Color finish deliver unmatched strength, leak resistance, and long lasting durability to withstand nature’s toughest weather. Designed for quick, low maintenance installation, these high-quality sheets fit together seamlessly to keep your building completely protected, ensuring a smart, reliable investment that stands the test of time.',
      images: [
        '/images/sample-products/p1-1.jpg',
        '/images/sample-products/p1-2.jpg',
      ],
      price: 3870,
      brand: 'Rhino',
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: '/images/banner-1.jpg',
    },
    {
      name: 'Nippon Roofing Paint - Water Base',
      slug: 'Nippon-Roofing-Paint---Water-Base',
      category: "Paint",
      description: 'Premium acrylic water-based roof coating specially engineered for exterior roofing and architectural surfaces. Durable, flexible, and enriched with biocides and algaecides to resist mold, algae, and microbial growth. Delivers outstanding adhesion, excellent coverage, and long-lasting protection against harsh tropical climates while enhancing surface appearance and durability. Formulated to resist peeling, cracking, and fading, ensuring reliable performance and lasting colour retention in demanding weather conditions.',
      images: [
        '/images/sample-products/p2-1.jpg',
        '/images/sample-products/p2-2.jpg',
      ],
      price: 2312,
      brand: 'Nippon',
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: '/images/banner-2.jpg',
    },
    {
      name: 'Nippon Wall Filler',
      slug: 'nippon-wall-filler',
      category: "Paint",
      description: 'Nippolac Acrylic Wall Filler is designed for interior plastered surfaces and previously painted walls, offering excellent filling properties. It effectively hides surface imperfections and helps achieve a smooth, high-quality finish. It also reduces paint absorption, helping to lower the cost of the first coat of paint while improving overall coverage and appearance.',
      images: [
        '/images/sample-products/p3-1.jpg',
        '/images/sample-products/p3-2.jpg',
      ],
      price: 712,
      brand: 'Nippon',
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Nippon Ceiling White',
      slug: 'nippon-ceiling-white',
      category: "Paint",
      description: 'Premium ceiling paint for a smooth, durable finish',
      images: [
        '/images/sample-products/p4-1.jpg',
        '/images/sample-products/p4-2.jpg',
      ],
      price: 1328,
      brand: 'Nippon',
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Nippon Weatherproof Brilliant White',
      slug: 'nippon-weatherproof-brilliant-white',
      category: "Paint",
      description: 'Nippolac Weatherproof Acrylic Exterior Emulsion is specially formulated to provide a durable and attractive finish for exterior walls. Its tough and flexible composition contains biocides and algaecides that help prevent the growth of mould, algae, and other microorganisms. Resistant to salt spray and designed to withstand harsh tropical weather conditions, it offers long-lasting protection while enhancing the appearance of exterior surfaces.',
      images: [
        '/images/sample-products/p5-1.jpg',
        '/images/sample-products/p5-2.jpg',
      ],
      price: 2184,
      brand: 'Nippon',
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Nippon Weatherproof - Colors',
      slug: 'nippon-weatherproof-colors',
      category: "Paint",
      description: 'Nippolac Weatherproof Acrylic Exterior Emulsion is specially formulated to provide a durable and attractive finish for exterior walls. Its tough and flexible composition contains biocides and algaecides that help prevent the growth of mould, algae, and other microorganisms. Resistant to salt spray and designed to withstand harsh tropical weather conditions, it offers long-lasting protection while enhancing the appearance of exterior surfaces.',
      images: [
        '/images/sample-products/p6-1.jpg',
        '/images/sample-products/p6-2.jpg',
      ],
      price: 2512,
      brand: 'Nippon',
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
    {
      name: '13 A Socket - Kevilton Electric Socket Product',
      slug: '13-a-socket-kevilton-electric-socket-product',
      category: "Electrical",
      description: 'Kevilton 13A Socket is a high-quality electrical socket designed for safe and reliable power distribution. It features a durable construction, ensuring long-lasting performance and resistance to wear and tear. The socket is easy to install and provides a secure connection for various electrical devices, making it an essential component for residential and commercial electrical systems.',
      images: [
        '/images/sample-products/p7-1.jpg',
        '/images/sample-products/p7-2.jpg',
      ],
      price: 1045,
      brand: 'Kevilton',
      rating: 4.1,
      numReviews: 1,
      stock: 50,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Orange LED Bulbs (W/W) Screw Type (E27)',
      slug: 'orange-led-bulbs-w-w-screw-type-e27',
      category: "Electrical",
      description: 'Orange LED Bulbs are energy-efficient lighting solutions designed for residential and commercial use. These bulbs provide bright, warm white light with a color temperature of 2700K, creating a cozy and inviting atmosphere. The screw-type E27 base ensures easy installation in standard light fixtures. With their long lifespan and low energy consumption, these LED bulbs offer an eco-friendly alternative to traditional incandescent bulbs, helping to reduce electricity costs while maintaining high-quality illumination.',
      images: [
        '/images/sample-products/p8-1.jpg',
        '/images/sample-products/p8-2.jpg',
      ],
      price: 420,
      brand: 'OREL CORPORATE',
      rating: 4.7,
      numReviews: 12,
      stock: 80,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'National Garden Hose Blue 1"',
      slug: 'national-garden-hose-blue-1',
      category: "Plumbing",
      description: 'National Garden Hose Blue 1" is a durable and flexible hose designed for efficient water delivery in gardening and outdoor applications. Made from high-quality materials, it offers excellent resistance to kinking, abrasion, and UV exposure, ensuring long-lasting performance. The hose features a smooth interior for optimal water flow and is compatible with standard fittings for easy connection to faucets and sprinklers. Ideal for watering plants, cleaning outdoor surfaces, and other general-purpose tasks, this garden hose provides reliable functionality for all your outdoor needs.',
      images: [
        '/images/sample-products/p9-1.jpg',
        '/images/sample-products/p9-2.jpg',
      ],
      price: 8085,
      brand: 'National PVC',
      rating: 4.1,
      numReviews: 1,
      stock: 50,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Reducing Socket - National',
      slug: 'reducing-socket-national',
      category: "Plumbing",
      description: 'National Reducing Socket is a high-quality plumbing fitting designed to connect pipes of different diameters securely. Made from durable materials, it ensures leak-free performance and long-lasting reliability in various plumbing applications. The socket features a smooth interior for optimal water flow and is easy to install, making it an essential component for residential and commercial plumbing systems. Ideal for reducing pipe sizes in water supply lines, this reducing socket provides a dependable solution for efficient fluid management.',
      images: [
        '/images/sample-products/p10-1.jpg',
        '/images/sample-products/p10-2.jpg',
      ],
      price: 70,
      brand: 'National PVC',
      rating: 4.7,
      numReviews: 12,
      stock: 80,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Rubber Coated Gloves - Heavy Duty',
      slug: 'rubber-coated-gloves-heavy-duty',
      category: "Safety Items",
      description: 'Rubber Coated Gloves are designed for heavy-duty applications, providing superior grip, protection, and durability. The gloves feature a robust rubber coating that enhances resistance to abrasions, cuts, and punctures, making them ideal for handling rough or sharp objects. The comfortable inner lining ensures a snug fit while allowing flexibility and dexterity for various tasks. Suitable for industrial work, construction, gardening, and other demanding environments, these gloves offer reliable hand protection and improved safety during manual labor.',
      images: [
        '/images/sample-products/p11-1.jpg',
        '/images/sample-products/p11-2.jpg',
      ],
      price: 414,
      brand: 'KLASS',
      rating: 3.7,
      numReviews: 12,
      stock: 20,
      isFeatured: false,
      banner: null,
    },
  ],
};

export default sampleData;
